"""Project-wide constants for window, maze, and entity behavior."""

from __future__ import annotations

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768
WINDOW_TITLE = "Pac-Man"

CLOSED_NORTH = 0b0001
CLOSED_EAST = 0b0010
CLOSED_SOUTH = 0b0100
CLOSED_WEST = 0b1000

PLAYER_MOVEMENT_SPEED = 10
PLAYER_CELL_FRACTION = 0.9
ITEM_CELL_FRACTION = 0.45
PACGUM_ANIMATION_FPS = 8.0
MAZE_MARGIN = 12.0
PLAYER_SPEED_RATIO = 0.09
MAX_COLLISION_WALL_THICKNESS = 4.0
COLLISION_WALL_THICKNESS_RATIO = 0.08
