"""Core configuration, types, and utilities."""

from pacman.core.config import GameConfig, Parser
from pacman.core.constants import (
    CLOSED_EAST,
    CLOSED_NORTH,
    CLOSED_SOUTH,
    CLOSED_WEST,
    COLLISION_WALL_THICKNESS_RATIO,
    GHOST_ANIMATION_FPS,
    GHOST_CELL_FRACTION,
    GHOST_SPEED_RATIO,
    ITEM_CELL_FRACTION,
    MAX_COLLISION_WALL_THICKNESS,
    MAZE_MARGIN,
    PACGUM_ANIMATION_FPS,
    PLAYER_CELL_FRACTION,
    PLAYER_MOVEMENT_SPEED,
    PLAYER_SPEED_RATIO,
    WINDOW_HEIGHT,
    WINDOW_TITLE,
    WINDOW_WIDTH,
)
from pacman.core.types import Direction, GridPoint, WallCollider, WallSegment
from pacman.core.utils import (
    center_cell_index,
    choose_initial_direction,
    coerce_blocked_directions,
    direction_is_open,
    nearest_cell_center,
    nearest_cell_index,
    normalize_segment,
    resolve_direction,
)

__all__ = [
    "GameConfig",
    "Parser",
    "CLOSED_EAST",
    "CLOSED_NORTH",
    "CLOSED_SOUTH",
    "CLOSED_WEST",
    "COLLISION_WALL_THICKNESS_RATIO",
    "GHOST_ANIMATION_FPS",
    "GHOST_CELL_FRACTION",
    "GHOST_SPEED_RATIO",
    "ITEM_CELL_FRACTION",
    "MAX_COLLISION_WALL_THICKNESS",
    "MAZE_MARGIN",
    "PACGUM_ANIMATION_FPS",
    "PLAYER_CELL_FRACTION",
    "PLAYER_MOVEMENT_SPEED",
    "PLAYER_SPEED_RATIO",
    "WINDOW_HEIGHT",
    "WINDOW_TITLE",
    "WINDOW_WIDTH",
    "Direction",
    "GridPoint",
    "WallCollider",
    "WallSegment",
    "center_cell_index",
    "choose_initial_direction",
    "coerce_blocked_directions",
    "direction_is_open",
    "nearest_cell_center",
    "nearest_cell_index",
    "normalize_segment",
    "resolve_direction",
]
